// GLM 1.1.0 (337 ops) -- generated by tools/gen_ops.py.

// Generated by tools/gen_ops.py -- do not edit by hand.

#define GLM_VERSION_NUMBER ((1 << 16) | (1 << 8) | 0)
#include <cstring>
#include <glm/glm.hpp>
#include <glm/gtc/quaternion.hpp>
#include <glm/ext/matrix_transform.hpp>
#include <glm/ext/matrix_clip_space.hpp>
#include "glm_wrapper.h"

enum : int {
    OP_SIN,
    OP_COS,
    OP_TAN,
    OP_ASIN,
    OP_ACOS,
    OP_ATAN,
    OP_SINH,
    OP_COSH,
    OP_TANH,
    OP_ASINH,
    OP_ACOSH,
    OP_ATANH,
    OP_RADIANS,
    OP_DEGREES,
    OP_ABS,
    OP_SIGN,
    OP_FLOOR,
    OP_CEIL,
    OP_FRACT,
    OP_TRUNC,
    OP_ROUND,
    OP_ROUNDEVEN,
    OP_SQRT,
    OP_INVERSESQRT,
    OP_EXP,
    OP_LOG,
    OP_EXP2,
    OP_LOG2,
    OP_ATAN2,
    OP_POW,
    OP_MOD,
    OP_MIN,
    OP_MAX,
    OP_STEP,
    OP_CLAMP,
    OP_MIX,
    OP_SMOOTHSTEP,
    OP_FMA,
    OP_IS_NAN,
    OP_IS_INF,
    OP_VEC2_ADD,
    OP_VEC2_SUB,
    OP_VEC2_MUL,
    OP_VEC2_DIV,
    OP_VEC2_SCALE,
    OP_VEC2_DIV_S,
    OP_VEC2_NEG,
    OP_VEC2_DOT,
    OP_VEC2_LENGTH,
    OP_VEC2_DISTANCE,
    OP_VEC2_NORMALIZE,
    OP_VEC2_CLAMP,
    OP_VEC2_CLAMP_V,
    OP_VEC2_MIX,
    OP_VEC2_MIX_V,
    OP_VEC2_MIN,
    OP_VEC2_MAX,
    OP_VEC2_MIN_S,
    OP_VEC2_MAX_S,
    OP_VEC2_REFLECT,
    OP_VEC2_REFRACT,
    OP_VEC2_FACEFORWARD,
    OP_VEC2_STEP,
    OP_VEC2_STEP_S,
    OP_VEC2_SMOOTHSTEP,
    OP_VEC2_SMOOTHSTEP_V,
    OP_VEC2_ANY,
    OP_VEC2_ALL,
    OP_VEC2_EQUAL,
    OP_VEC2_NOT_EQUAL,
    OP_VEC2_LESS,
    OP_VEC2_LESS_EQUAL,
    OP_VEC2_GREATER,
    OP_VEC2_GREATER_EQUAL,
    OP_VEC2_ABS,
    OP_VEC2_SIGN,
    OP_VEC2_FLOOR,
    OP_VEC2_CEIL,
    OP_VEC2_FRACT,
    OP_VEC2_TRUNC,
    OP_VEC2_ROUND,
    OP_VEC2_ROUNDEVEN,
    OP_VEC2_SQRT,
    OP_VEC2_INVERSESQRT,
    OP_VEC2_SIN,
    OP_VEC2_COS,
    OP_VEC2_TAN,
    OP_VEC2_ASIN,
    OP_VEC2_ACOS,
    OP_VEC2_ATAN,
    OP_VEC2_SINH,
    OP_VEC2_COSH,
    OP_VEC2_TANH,
    OP_VEC2_EXP,
    OP_VEC2_LOG,
    OP_VEC2_EXP2,
    OP_VEC2_LOG2,
    OP_VEC2_RADIANS,
    OP_VEC2_DEGREES,
    OP_VEC2_ATAN2,
    OP_VEC2_POW,
    OP_VEC2_MOD,
    OP_VEC2_MOD_S,
    OP_VEC2_FMA,
    OP_VEC2_IS_NAN,
    OP_VEC2_IS_INF,
    OP_VEC3_ADD,
    OP_VEC3_SUB,
    OP_VEC3_MUL,
    OP_VEC3_DIV,
    OP_VEC3_SCALE,
    OP_VEC3_DIV_S,
    OP_VEC3_NEG,
    OP_VEC3_DOT,
    OP_VEC3_LENGTH,
    OP_VEC3_DISTANCE,
    OP_VEC3_NORMALIZE,
    OP_VEC3_CLAMP,
    OP_VEC3_CLAMP_V,
    OP_VEC3_MIX,
    OP_VEC3_MIX_V,
    OP_VEC3_MIN,
    OP_VEC3_MAX,
    OP_VEC3_MIN_S,
    OP_VEC3_MAX_S,
    OP_VEC3_REFLECT,
    OP_VEC3_REFRACT,
    OP_VEC3_FACEFORWARD,
    OP_VEC3_STEP,
    OP_VEC3_STEP_S,
    OP_VEC3_SMOOTHSTEP,
    OP_VEC3_SMOOTHSTEP_V,
    OP_VEC3_ANY,
    OP_VEC3_ALL,
    OP_VEC3_EQUAL,
    OP_VEC3_NOT_EQUAL,
    OP_VEC3_LESS,
    OP_VEC3_LESS_EQUAL,
    OP_VEC3_GREATER,
    OP_VEC3_GREATER_EQUAL,
    OP_VEC3_ABS,
    OP_VEC3_SIGN,
    OP_VEC3_FLOOR,
    OP_VEC3_CEIL,
    OP_VEC3_FRACT,
    OP_VEC3_TRUNC,
    OP_VEC3_ROUND,
    OP_VEC3_ROUNDEVEN,
    OP_VEC3_SQRT,
    OP_VEC3_INVERSESQRT,
    OP_VEC3_SIN,
    OP_VEC3_COS,
    OP_VEC3_TAN,
    OP_VEC3_ASIN,
    OP_VEC3_ACOS,
    OP_VEC3_ATAN,
    OP_VEC3_SINH,
    OP_VEC3_COSH,
    OP_VEC3_TANH,
    OP_VEC3_EXP,
    OP_VEC3_LOG,
    OP_VEC3_EXP2,
    OP_VEC3_LOG2,
    OP_VEC3_RADIANS,
    OP_VEC3_DEGREES,
    OP_VEC3_ATAN2,
    OP_VEC3_POW,
    OP_VEC3_MOD,
    OP_VEC3_MOD_S,
    OP_VEC3_FMA,
    OP_VEC3_IS_NAN,
    OP_VEC3_IS_INF,
    OP_VEC4_ADD,
    OP_VEC4_SUB,
    OP_VEC4_MUL,
    OP_VEC4_DIV,
    OP_VEC4_SCALE,
    OP_VEC4_DIV_S,
    OP_VEC4_NEG,
    OP_VEC4_DOT,
    OP_VEC4_LENGTH,
    OP_VEC4_DISTANCE,
    OP_VEC4_NORMALIZE,
    OP_VEC4_CLAMP,
    OP_VEC4_CLAMP_V,
    OP_VEC4_MIX,
    OP_VEC4_MIX_V,
    OP_VEC4_MIN,
    OP_VEC4_MAX,
    OP_VEC4_MIN_S,
    OP_VEC4_MAX_S,
    OP_VEC4_REFLECT,
    OP_VEC4_REFRACT,
    OP_VEC4_FACEFORWARD,
    OP_VEC4_STEP,
    OP_VEC4_STEP_S,
    OP_VEC4_SMOOTHSTEP,
    OP_VEC4_SMOOTHSTEP_V,
    OP_VEC4_ANY,
    OP_VEC4_ALL,
    OP_VEC4_EQUAL,
    OP_VEC4_NOT_EQUAL,
    OP_VEC4_LESS,
    OP_VEC4_LESS_EQUAL,
    OP_VEC4_GREATER,
    OP_VEC4_GREATER_EQUAL,
    OP_VEC4_ABS,
    OP_VEC4_SIGN,
    OP_VEC4_FLOOR,
    OP_VEC4_CEIL,
    OP_VEC4_FRACT,
    OP_VEC4_TRUNC,
    OP_VEC4_ROUND,
    OP_VEC4_ROUNDEVEN,
    OP_VEC4_SQRT,
    OP_VEC4_INVERSESQRT,
    OP_VEC4_SIN,
    OP_VEC4_COS,
    OP_VEC4_TAN,
    OP_VEC4_ASIN,
    OP_VEC4_ACOS,
    OP_VEC4_ATAN,
    OP_VEC4_SINH,
    OP_VEC4_COSH,
    OP_VEC4_TANH,
    OP_VEC4_EXP,
    OP_VEC4_LOG,
    OP_VEC4_EXP2,
    OP_VEC4_LOG2,
    OP_VEC4_RADIANS,
    OP_VEC4_DEGREES,
    OP_VEC4_ATAN2,
    OP_VEC4_POW,
    OP_VEC4_MOD,
    OP_VEC4_MOD_S,
    OP_VEC4_FMA,
    OP_VEC4_IS_NAN,
    OP_VEC4_IS_INF,
    OP_VEC3_CROSS,
    OP_VEC2_FROM,
    OP_VEC3_FROM,
    OP_VEC4_FROM,
    OP_MAT2_IDENTITY,
    OP_MAT2_ZERO,
    OP_MAT2_ADD,
    OP_MAT2_SUB,
    OP_MAT2_MUL,
    OP_MAT2_MUL_VEC,
    OP_MAT2_MUL_S,
    OP_MAT2_DIV_S,
    OP_MAT2_NEG,
    OP_MAT2_TRANSPOSE,
    OP_MAT2_INVERSE,
    OP_MAT2_DETERMINANT,
    OP_MAT2_TRACE,
    OP_MAT2_COMP_MUL,
    OP_MAT3_IDENTITY,
    OP_MAT3_ZERO,
    OP_MAT3_ADD,
    OP_MAT3_SUB,
    OP_MAT3_MUL,
    OP_MAT3_MUL_VEC,
    OP_MAT3_MUL_S,
    OP_MAT3_DIV_S,
    OP_MAT3_NEG,
    OP_MAT3_TRANSPOSE,
    OP_MAT3_INVERSE,
    OP_MAT3_DETERMINANT,
    OP_MAT3_TRACE,
    OP_MAT3_COMP_MUL,
    OP_MAT4_IDENTITY,
    OP_MAT4_ZERO,
    OP_MAT4_ADD,
    OP_MAT4_SUB,
    OP_MAT4_MUL,
    OP_MAT4_MUL_VEC,
    OP_MAT4_MUL_S,
    OP_MAT4_DIV_S,
    OP_MAT4_NEG,
    OP_MAT4_TRANSPOSE,
    OP_MAT4_INVERSE,
    OP_MAT4_DETERMINANT,
    OP_MAT4_TRACE,
    OP_MAT4_COMP_MUL,
    OP_MAT2_FROM,
    OP_MAT3_FROM,
    OP_MAT4_FROM,
    OP_MAT3_TO_MAT4,
    OP_MAT4_TO_MAT3,
    OP_MAT4_TRANSLATE,
    OP_MAT4_TRANSLATE_XYZ,
    OP_MAT4_ROTATE,
    OP_MAT4_ROTATE_X,
    OP_MAT4_ROTATE_Y,
    OP_MAT4_ROTATE_Z,
    OP_MAT4_SCALE,
    OP_MAT4_SCALE_XYZ,
    OP_MAT4_PERSPECTIVE,
    OP_MAT4_PERSPECTIVE_LH,
    OP_MAT4_PERSPECTIVE_RH,
    OP_MAT4_ORTHO,
    OP_MAT4_ORTHO_LH,
    OP_MAT4_ORTHO_RH,
    OP_MAT4_FRUSTUM,
    OP_MAT4_FRUSTUM_LH,
    OP_MAT4_FRUSTUM_RH,
    OP_MAT4_LOOK_AT,
    OP_MAT4_LOOK_AT_LH,
    OP_MAT4_LOOK_AT_RH,
    OP_QUAT_IDENTITY,
    OP_QUAT_ADD,
    OP_QUAT_SUB,
    OP_QUAT_MUL,
    OP_QUAT_MUL_VEC3,
    OP_QUAT_SCALE,
    OP_QUAT_NEG,
    OP_QUAT_CONJUGATE,
    OP_QUAT_INVERSE,
    OP_QUAT_NORMALIZE,
    OP_QUAT_DOT,
    OP_QUAT_LENGTH,
    OP_QUAT_CROSS,
    OP_QUAT_LERP,
    OP_QUAT_SLERP,
    OP_QUAT_AXIS_ANGLE,
    OP_QUAT_ANGLE,
    OP_QUAT_AXIS,
    OP_QUAT_ROTATE,
    OP_QUAT_PITCH,
    OP_QUAT_YAW,
    OP_QUAT_ROLL,
    OP_QUAT_EULER_ANGLES,
    OP_QUAT_TO_MAT4,
    OP_QUAT_TO_MAT3,
    OP_MAT4_TO_QUAT,
    OP_MAT3_TO_QUAT,
    OP_QUAT_FROM,
    OP_COUNT,
};

namespace {
struct Input {
    const float* p;
    explicit Input(const float* ptr) : p(ptr) {}
    float next() { float v = *p; ++p; return v; }
    const float* next(int n) { const float* r = p; p += n; return r; }
};
}

extern "C" int glm_op_count(void) { return OP_COUNT; }

extern "C" int glm_version(void) { return GLM_VERSION_NUMBER; }

extern "C" void glm_call(int op, const float* args, int arg_count, float* out, int out_count) {
    (void)arg_count; (void)out_count;
    Input e(args);
    switch (op) {
    case OP_SIN: {
        float s = e.next();
        float r = glm::sin(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_COS: {
        float s = e.next();
        float r = glm::cos(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_TAN: {
        float s = e.next();
        float r = glm::tan(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_ASIN: {
        float s = e.next();
        float r = glm::asin(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_ACOS: {
        float s = e.next();
        float r = glm::acos(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_ATAN: {
        float s = e.next();
        float r = glm::atan(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_SINH: {
        float s = e.next();
        float r = glm::sinh(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_COSH: {
        float s = e.next();
        float r = glm::cosh(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_TANH: {
        float s = e.next();
        float r = glm::tanh(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_ASINH: {
        float s = e.next();
        float r = glm::asinh(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_ACOSH: {
        float s = e.next();
        float r = glm::acosh(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_ATANH: {
        float s = e.next();
        float r = glm::atanh(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_RADIANS: {
        float s = e.next();
        float r = glm::radians(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_DEGREES: {
        float s = e.next();
        float r = glm::degrees(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_ABS: {
        float s = e.next();
        float r = glm::abs(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_SIGN: {
        float s = e.next();
        float r = glm::sign(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_FLOOR: {
        float s = e.next();
        float r = glm::floor(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_CEIL: {
        float s = e.next();
        float r = glm::ceil(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_FRACT: {
        float s = e.next();
        float r = glm::fract(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_TRUNC: {
        float s = e.next();
        float r = glm::trunc(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_ROUND: {
        float s = e.next();
        float r = glm::round(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_ROUNDEVEN: {
        float s = e.next();
        float r = glm::roundEven(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_SQRT: {
        float s = e.next();
        float r = glm::sqrt(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_INVERSESQRT: {
        float s = e.next();
        float r = glm::inversesqrt(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_EXP: {
        float s = e.next();
        float r = glm::exp(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_LOG: {
        float s = e.next();
        float r = glm::log(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_EXP2: {
        float s = e.next();
        float r = glm::exp2(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_LOG2: {
        float s = e.next();
        float r = glm::log2(s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_ATAN2: {
        float s = e.next();
        float t = e.next();
        float r = glm::atan(s, t); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_POW: {
        float s = e.next();
        float t = e.next();
        float r = glm::pow(s, t); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MOD: {
        float s = e.next();
        float t = e.next();
        float r = glm::mod(s, t); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MIN: {
        float s = e.next();
        float t = e.next();
        float r = glm::min(s, t); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAX: {
        float s = e.next();
        float t = e.next();
        float r = glm::max(s, t); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_STEP: {
        float s = e.next();
        float t = e.next();
        float r = glm::step(s, t); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_CLAMP: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float r = glm::clamp(s, t, u); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MIX: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float r = glm::mix(s, t, u); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_SMOOTHSTEP: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float r = glm::smoothstep(s, t, u); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_FMA: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float r = glm::fma(s, t, u); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_IS_NAN: {
        float s = e.next();
        out[0] = (glm::isnan(s)) ? 1.0f : 0.0f;
        break;
    }
    case OP_IS_INF: {
        float s = e.next();
        out[0] = (glm::isinf(s)) ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC2_ADD: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 r = a + b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_SUB: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 r = a - b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_MUL: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 r = a * b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_DIV: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 r = a / b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_SCALE: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        float s = e.next();
        glm::vec2 r = a * s; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_DIV_S: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        float s = e.next();
        glm::vec2 r = a / s; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_NEG: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = -a; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_DOT: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        float r = glm::dot(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_LENGTH: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        float r = glm::length(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_DISTANCE: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        float r = glm::distance(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_NORMALIZE: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::normalize(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_CLAMP: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        float s = e.next();
        float t = e.next();
        glm::vec2 r = glm::clamp(a, s, t); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_CLAMP_V: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 c; memcpy(&c, e.next(2), 8);
        glm::vec2 r = glm::clamp(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_MIX: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        float s = e.next();
        glm::vec2 r = glm::mix(a, b, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_MIX_V: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 c; memcpy(&c, e.next(2), 8);
        glm::vec2 r = glm::mix(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_MIN: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 r = glm::min(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_MAX: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 r = glm::max(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_MIN_S: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        float s = e.next();
        glm::vec2 r = glm::min(a, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_MAX_S: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        float s = e.next();
        glm::vec2 r = glm::max(a, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_REFLECT: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 r = glm::reflect(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_REFRACT: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        float s = e.next();
        glm::vec2 r = glm::refract(a, b, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_FACEFORWARD: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 c; memcpy(&c, e.next(2), 8);
        glm::vec2 r = glm::faceforward(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_STEP: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 r = glm::step(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_STEP_S: {
        float s = e.next();
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::step(s, a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_SMOOTHSTEP: {
        float s = e.next();
        float t = e.next();
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::smoothstep(s, t, a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_SMOOTHSTEP_V: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 c; memcpy(&c, e.next(2), 8);
        glm::vec2 r = glm::smoothstep(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_ANY: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        out[0] = (glm::any(glm::notEqual(a, glm::vec2(0.0f)))) ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC2_ALL: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        out[0] = (glm::all(glm::notEqual(a, glm::vec2(0.0f)))) ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC2_EQUAL: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        out[0] = (glm::all(glm::equal(a, b))) ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC2_NOT_EQUAL: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        out[0] = (glm::any(glm::notEqual(a, b))) ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC2_LESS: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::bvec2 r = glm::lessThan(a, b); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC2_LESS_EQUAL: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::bvec2 r = glm::lessThanEqual(a, b); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC2_GREATER: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::bvec2 r = glm::greaterThan(a, b); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC2_GREATER_EQUAL: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::bvec2 r = glm::greaterThanEqual(a, b); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC2_ABS: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::abs(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_SIGN: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::sign(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_FLOOR: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::floor(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_CEIL: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::ceil(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_FRACT: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::fract(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_TRUNC: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::trunc(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_ROUND: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::round(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_ROUNDEVEN: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::roundEven(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_SQRT: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::sqrt(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_INVERSESQRT: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::inversesqrt(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_SIN: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::sin(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_COS: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::cos(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_TAN: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::tan(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_ASIN: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::asin(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_ACOS: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::acos(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_ATAN: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::atan(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_SINH: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::sinh(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_COSH: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::cosh(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_TANH: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::tanh(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_EXP: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::exp(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_LOG: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::log(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_EXP2: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::exp2(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_LOG2: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::log2(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_RADIANS: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::radians(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_DEGREES: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 r = glm::degrees(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_ATAN2: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 r = glm::atan(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_POW: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 r = glm::pow(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_MOD: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 r = glm::mod(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_MOD_S: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        float s = e.next();
        glm::vec2 r = glm::mod(a, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_FMA: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 c; memcpy(&c, e.next(2), 8);
        glm::vec2 r = glm::fma(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_IS_NAN: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::bvec2 r = glm::isnan(a); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC2_IS_INF: {
        glm::vec2 a; memcpy(&a, e.next(2), 8);
        glm::bvec2 r = glm::isinf(a); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC3_ADD: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = a + b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_SUB: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = a - b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_MUL: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = a * b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_DIV: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = a / b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_SCALE: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        float s = e.next();
        glm::vec3 r = a * s; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_DIV_S: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        float s = e.next();
        glm::vec3 r = a / s; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_NEG: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = -a; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_DOT: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        float r = glm::dot(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_LENGTH: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        float r = glm::length(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_DISTANCE: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        float r = glm::distance(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_NORMALIZE: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::normalize(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_CLAMP: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        float s = e.next();
        float t = e.next();
        glm::vec3 r = glm::clamp(a, s, t); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_CLAMP_V: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 c; memcpy(&c, e.next(3), 12);
        glm::vec3 r = glm::clamp(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_MIX: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        float s = e.next();
        glm::vec3 r = glm::mix(a, b, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_MIX_V: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 c; memcpy(&c, e.next(3), 12);
        glm::vec3 r = glm::mix(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_MIN: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = glm::min(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_MAX: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = glm::max(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_MIN_S: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        float s = e.next();
        glm::vec3 r = glm::min(a, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_MAX_S: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        float s = e.next();
        glm::vec3 r = glm::max(a, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_REFLECT: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = glm::reflect(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_REFRACT: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        float s = e.next();
        glm::vec3 r = glm::refract(a, b, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_FACEFORWARD: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 c; memcpy(&c, e.next(3), 12);
        glm::vec3 r = glm::faceforward(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_STEP: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = glm::step(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_STEP_S: {
        float s = e.next();
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::step(s, a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_SMOOTHSTEP: {
        float s = e.next();
        float t = e.next();
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::smoothstep(s, t, a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_SMOOTHSTEP_V: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 c; memcpy(&c, e.next(3), 12);
        glm::vec3 r = glm::smoothstep(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_ANY: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        out[0] = (glm::any(glm::notEqual(a, glm::vec3(0.0f)))) ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC3_ALL: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        out[0] = (glm::all(glm::notEqual(a, glm::vec3(0.0f)))) ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC3_EQUAL: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        out[0] = (glm::all(glm::equal(a, b))) ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC3_NOT_EQUAL: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        out[0] = (glm::any(glm::notEqual(a, b))) ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC3_LESS: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::bvec3 r = glm::lessThan(a, b); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f; out[2] = r[2] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC3_LESS_EQUAL: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::bvec3 r = glm::lessThanEqual(a, b); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f; out[2] = r[2] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC3_GREATER: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::bvec3 r = glm::greaterThan(a, b); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f; out[2] = r[2] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC3_GREATER_EQUAL: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::bvec3 r = glm::greaterThanEqual(a, b); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f; out[2] = r[2] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC3_ABS: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::abs(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_SIGN: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::sign(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_FLOOR: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::floor(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_CEIL: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::ceil(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_FRACT: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::fract(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_TRUNC: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::trunc(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_ROUND: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::round(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_ROUNDEVEN: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::roundEven(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_SQRT: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::sqrt(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_INVERSESQRT: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::inversesqrt(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_SIN: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::sin(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_COS: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::cos(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_TAN: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::tan(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_ASIN: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::asin(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_ACOS: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::acos(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_ATAN: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::atan(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_SINH: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::sinh(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_COSH: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::cosh(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_TANH: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::tanh(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_EXP: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::exp(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_LOG: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::log(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_EXP2: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::exp2(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_LOG2: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::log2(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_RADIANS: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::radians(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_DEGREES: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 r = glm::degrees(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_ATAN2: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = glm::atan(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_POW: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = glm::pow(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_MOD: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = glm::mod(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_MOD_S: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        float s = e.next();
        glm::vec3 r = glm::mod(a, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_FMA: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 c; memcpy(&c, e.next(3), 12);
        glm::vec3 r = glm::fma(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_IS_NAN: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::bvec3 r = glm::isnan(a); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f; out[2] = r[2] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC3_IS_INF: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::bvec3 r = glm::isinf(a); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f; out[2] = r[2] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC4_ADD: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 r = a + b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_SUB: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 r = a - b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_MUL: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 r = a * b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_DIV: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 r = a / b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_SCALE: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        float s = e.next();
        glm::vec4 r = a * s; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_DIV_S: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        float s = e.next();
        glm::vec4 r = a / s; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_NEG: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = -a; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_DOT: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        float r = glm::dot(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_LENGTH: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        float r = glm::length(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_DISTANCE: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        float r = glm::distance(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_NORMALIZE: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::normalize(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_CLAMP: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        float s = e.next();
        float t = e.next();
        glm::vec4 r = glm::clamp(a, s, t); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_CLAMP_V: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 c; memcpy(&c, e.next(4), 16);
        glm::vec4 r = glm::clamp(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_MIX: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        float s = e.next();
        glm::vec4 r = glm::mix(a, b, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_MIX_V: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 c; memcpy(&c, e.next(4), 16);
        glm::vec4 r = glm::mix(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_MIN: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 r = glm::min(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_MAX: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 r = glm::max(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_MIN_S: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        float s = e.next();
        glm::vec4 r = glm::min(a, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_MAX_S: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        float s = e.next();
        glm::vec4 r = glm::max(a, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_REFLECT: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 r = glm::reflect(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_REFRACT: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        float s = e.next();
        glm::vec4 r = glm::refract(a, b, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_FACEFORWARD: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 c; memcpy(&c, e.next(4), 16);
        glm::vec4 r = glm::faceforward(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_STEP: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 r = glm::step(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_STEP_S: {
        float s = e.next();
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::step(s, a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_SMOOTHSTEP: {
        float s = e.next();
        float t = e.next();
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::smoothstep(s, t, a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_SMOOTHSTEP_V: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 c; memcpy(&c, e.next(4), 16);
        glm::vec4 r = glm::smoothstep(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_ANY: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        out[0] = (glm::any(glm::notEqual(a, glm::vec4(0.0f)))) ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC4_ALL: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        out[0] = (glm::all(glm::notEqual(a, glm::vec4(0.0f)))) ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC4_EQUAL: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        out[0] = (glm::all(glm::equal(a, b))) ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC4_NOT_EQUAL: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        out[0] = (glm::any(glm::notEqual(a, b))) ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC4_LESS: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::bvec4 r = glm::lessThan(a, b); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f; out[2] = r[2] ? 1.0f : 0.0f; out[3] = r[3] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC4_LESS_EQUAL: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::bvec4 r = glm::lessThanEqual(a, b); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f; out[2] = r[2] ? 1.0f : 0.0f; out[3] = r[3] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC4_GREATER: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::bvec4 r = glm::greaterThan(a, b); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f; out[2] = r[2] ? 1.0f : 0.0f; out[3] = r[3] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC4_GREATER_EQUAL: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::bvec4 r = glm::greaterThanEqual(a, b); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f; out[2] = r[2] ? 1.0f : 0.0f; out[3] = r[3] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC4_ABS: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::abs(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_SIGN: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::sign(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_FLOOR: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::floor(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_CEIL: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::ceil(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_FRACT: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::fract(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_TRUNC: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::trunc(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_ROUND: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::round(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_ROUNDEVEN: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::roundEven(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_SQRT: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::sqrt(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_INVERSESQRT: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::inversesqrt(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_SIN: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::sin(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_COS: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::cos(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_TAN: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::tan(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_ASIN: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::asin(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_ACOS: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::acos(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_ATAN: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::atan(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_SINH: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::sinh(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_COSH: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::cosh(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_TANH: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::tanh(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_EXP: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::exp(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_LOG: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::log(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_EXP2: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::exp2(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_LOG2: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::log2(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_RADIANS: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::radians(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_DEGREES: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 r = glm::degrees(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_ATAN2: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 r = glm::atan(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_POW: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 r = glm::pow(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_MOD: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 r = glm::mod(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_MOD_S: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        float s = e.next();
        glm::vec4 r = glm::mod(a, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_FMA: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 c; memcpy(&c, e.next(4), 16);
        glm::vec4 r = glm::fma(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_IS_NAN: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::bvec4 r = glm::isnan(a); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f; out[2] = r[2] ? 1.0f : 0.0f; out[3] = r[3] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC4_IS_INF: {
        glm::vec4 a; memcpy(&a, e.next(4), 16);
        glm::bvec4 r = glm::isinf(a); out[0] = r[0] ? 1.0f : 0.0f; out[1] = r[1] ? 1.0f : 0.0f; out[2] = r[2] ? 1.0f : 0.0f; out[3] = r[3] ? 1.0f : 0.0f;
        break;
    }
    case OP_VEC3_CROSS: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = glm::cross(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC2_FROM: {
        float s = e.next();
        float t = e.next();
        glm::vec2 r = glm::vec2(s, t); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC3_FROM: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        glm::vec3 r = glm::vec3(s, t, u); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_VEC4_FROM: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        glm::vec4 r = glm::vec4(s, t, u, v); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_IDENTITY: {
        glm::mat2 r = glm::mat2(1.0f); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_ZERO: {
        glm::mat2 r = glm::mat2(0.0f); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_ADD: {
        glm::mat2 a; memcpy(&a, e.next(4), 16);
        glm::mat2 b; memcpy(&b, e.next(4), 16);
        glm::mat2 r = a + b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_SUB: {
        glm::mat2 a; memcpy(&a, e.next(4), 16);
        glm::mat2 b; memcpy(&b, e.next(4), 16);
        glm::mat2 r = a - b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_MUL: {
        glm::mat2 a; memcpy(&a, e.next(4), 16);
        glm::mat2 b; memcpy(&b, e.next(4), 16);
        glm::mat2 r = a * b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_MUL_VEC: {
        glm::mat2 a; memcpy(&a, e.next(4), 16);
        glm::vec2 b; memcpy(&b, e.next(2), 8);
        glm::vec2 r = a * b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_MUL_S: {
        glm::mat2 a; memcpy(&a, e.next(4), 16);
        float s = e.next();
        glm::mat2 r = a * s; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_DIV_S: {
        glm::mat2 a; memcpy(&a, e.next(4), 16);
        float s = e.next();
        glm::mat2 r = a / s; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_NEG: {
        glm::mat2 a; memcpy(&a, e.next(4), 16);
        glm::mat2 r = -a; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_TRANSPOSE: {
        glm::mat2 a; memcpy(&a, e.next(4), 16);
        glm::mat2 r = glm::transpose(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_INVERSE: {
        glm::mat2 a; memcpy(&a, e.next(4), 16);
        glm::mat2 r = glm::inverse(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_DETERMINANT: {
        glm::mat2 a; memcpy(&a, e.next(4), 16);
        float r = glm::determinant(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_TRACE: {
        glm::mat2 a; memcpy(&a, e.next(4), 16);
        float r = a[0][0] + a[1][1]; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_COMP_MUL: {
        glm::mat2 a; memcpy(&a, e.next(4), 16);
        glm::mat2 b; memcpy(&b, e.next(4), 16);
        glm::mat2 r = glm::matrixCompMult(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_IDENTITY: {
        glm::mat3 r = glm::mat3(1.0f); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_ZERO: {
        glm::mat3 r = glm::mat3(0.0f); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_ADD: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        glm::mat3 b; memcpy(&b, e.next(9), 36);
        glm::mat3 r = a + b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_SUB: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        glm::mat3 b; memcpy(&b, e.next(9), 36);
        glm::mat3 r = a - b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_MUL: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        glm::mat3 b; memcpy(&b, e.next(9), 36);
        glm::mat3 r = a * b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_MUL_VEC: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = a * b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_MUL_S: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        float s = e.next();
        glm::mat3 r = a * s; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_DIV_S: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        float s = e.next();
        glm::mat3 r = a / s; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_NEG: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        glm::mat3 r = -a; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_TRANSPOSE: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        glm::mat3 r = glm::transpose(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_INVERSE: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        glm::mat3 r = glm::inverse(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_DETERMINANT: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        float r = glm::determinant(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_TRACE: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        float r = a[0][0] + a[1][1] + a[2][2]; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_COMP_MUL: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        glm::mat3 b; memcpy(&b, e.next(9), 36);
        glm::mat3 r = glm::matrixCompMult(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_IDENTITY: {
        glm::mat4 r = glm::mat4(1.0f); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_ZERO: {
        glm::mat4 r = glm::mat4(0.0f); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_ADD: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        glm::mat4 b; memcpy(&b, e.next(16), 64);
        glm::mat4 r = a + b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_SUB: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        glm::mat4 b; memcpy(&b, e.next(16), 64);
        glm::mat4 r = a - b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_MUL: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        glm::mat4 b; memcpy(&b, e.next(16), 64);
        glm::mat4 r = a * b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_MUL_VEC: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        glm::vec4 b; memcpy(&b, e.next(4), 16);
        glm::vec4 r = a * b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_MUL_S: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        float s = e.next();
        glm::mat4 r = a * s; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_DIV_S: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        float s = e.next();
        glm::mat4 r = a / s; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_NEG: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        glm::mat4 r = -a; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_TRANSPOSE: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        glm::mat4 r = glm::transpose(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_INVERSE: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        glm::mat4 r = glm::inverse(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_DETERMINANT: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        float r = glm::determinant(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_TRACE: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        float r = a[0][0] + a[1][1] + a[2][2] + a[3][3]; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_COMP_MUL: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        glm::mat4 b; memcpy(&b, e.next(16), 64);
        glm::mat4 r = glm::matrixCompMult(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT2_FROM: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        glm::mat2 r = glm::mat2(s, t, u, v); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_FROM: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        float w = e.next();
        float x = e.next();
        float y = e.next();
        float z = e.next();
        float aa = e.next();
        glm::mat3 r = glm::mat3(s, t, u, v, w, x, y, z, aa); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_FROM: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        float w = e.next();
        float x = e.next();
        float y = e.next();
        float z = e.next();
        float aa = e.next();
        float ab = e.next();
        float ac = e.next();
        float ad = e.next();
        float ae = e.next();
        float af = e.next();
        float ag = e.next();
        float ah = e.next();
        glm::mat4 r = glm::mat4(s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_TO_MAT4: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        glm::mat4 r = glm::mat4(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_TO_MAT3: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        glm::mat3 r = glm::mat3(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_TRANSLATE: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::mat4 r = glm::translate(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_TRANSLATE_XYZ: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        float s = e.next();
        float t = e.next();
        float u = e.next();
        glm::mat4 r = glm::translate(a, glm::vec3(s, t, u)); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_ROTATE: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        glm::mat4 r = glm::rotate(a, s, glm::vec3(t, u, v)); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_ROTATE_X: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        float s = e.next();
        glm::mat4 r = glm::rotate(a, s, glm::vec3(1.0f, 0.0f, 0.0f)); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_ROTATE_Y: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        float s = e.next();
        glm::mat4 r = glm::rotate(a, s, glm::vec3(0.0f, 1.0f, 0.0f)); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_ROTATE_Z: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        float s = e.next();
        glm::mat4 r = glm::rotate(a, s, glm::vec3(0.0f, 0.0f, 1.0f)); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_SCALE: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::mat4 r = glm::scale(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_SCALE_XYZ: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        float s = e.next();
        float t = e.next();
        float u = e.next();
        glm::mat4 r = glm::scale(a, glm::vec3(s, t, u)); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_PERSPECTIVE: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        glm::mat4 r = glm::perspective(s, t, u, v); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_PERSPECTIVE_LH: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        glm::mat4 r = glm::perspectiveLH(s, t, u, v); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_PERSPECTIVE_RH: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        glm::mat4 r = glm::perspectiveRH(s, t, u, v); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_ORTHO: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        float w = e.next();
        float x = e.next();
        glm::mat4 r = glm::ortho(s, t, u, v, w, x); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_ORTHO_LH: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        float w = e.next();
        float x = e.next();
        glm::mat4 r = glm::orthoLH(s, t, u, v, w, x); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_ORTHO_RH: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        float w = e.next();
        float x = e.next();
        glm::mat4 r = glm::orthoRH(s, t, u, v, w, x); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_FRUSTUM: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        float w = e.next();
        float x = e.next();
        glm::mat4 r = glm::frustum(s, t, u, v, w, x); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_FRUSTUM_LH: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        float w = e.next();
        float x = e.next();
        glm::mat4 r = glm::frustumLH(s, t, u, v, w, x); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_FRUSTUM_RH: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        float w = e.next();
        float x = e.next();
        glm::mat4 r = glm::frustumRH(s, t, u, v, w, x); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_LOOK_AT: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 c; memcpy(&c, e.next(3), 12);
        glm::mat4 r = glm::lookAt(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_LOOK_AT_LH: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 c; memcpy(&c, e.next(3), 12);
        glm::mat4 r = glm::lookAtLH(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_LOOK_AT_RH: {
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 c; memcpy(&c, e.next(3), 12);
        glm::mat4 r = glm::lookAtRH(a, b, c); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_IDENTITY: {
        glm::quat r = glm::quat(1.0f, 0.0f, 0.0f, 0.0f); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_ADD: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::quat b; memcpy(&b, e.next(4), 16);
        glm::quat r = a + b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_SUB: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::quat b; memcpy(&b, e.next(4), 16);
        glm::quat r = a - b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_MUL: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::quat b; memcpy(&b, e.next(4), 16);
        glm::quat r = a * b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_MUL_VEC3: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::vec3 b; memcpy(&b, e.next(3), 12);
        glm::vec3 r = a * b; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_SCALE: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        float s = e.next();
        glm::quat r = a * s; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_NEG: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::quat r = -a; memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_CONJUGATE: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::quat r = glm::conjugate(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_INVERSE: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::quat r = glm::inverse(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_NORMALIZE: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::quat r = glm::normalize(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_DOT: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::quat b; memcpy(&b, e.next(4), 16);
        float r = glm::dot(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_LENGTH: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        float r = glm::length(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_CROSS: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::quat b; memcpy(&b, e.next(4), 16);
        glm::quat r = glm::cross(a, b); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_LERP: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::quat b; memcpy(&b, e.next(4), 16);
        float s = e.next();
        glm::quat r = glm::lerp(a, b, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_SLERP: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::quat b; memcpy(&b, e.next(4), 16);
        float s = e.next();
        glm::quat r = glm::slerp(a, b, s); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_AXIS_ANGLE: {
        float s = e.next();
        glm::vec3 a; memcpy(&a, e.next(3), 12);
        glm::quat r = glm::angleAxis(s, a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_ANGLE: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        float r = glm::angle(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_AXIS: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::vec3 r = glm::axis(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_ROTATE: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        glm::quat r = glm::rotate(a, s, glm::vec3(t, u, v)); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_PITCH: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        float r = glm::pitch(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_YAW: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        float r = glm::yaw(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_ROLL: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        float r = glm::roll(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_EULER_ANGLES: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::vec3 r = glm::eulerAngles(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_TO_MAT4: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::mat4 r = glm::mat4_cast(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_TO_MAT3: {
        glm::quat a; memcpy(&a, e.next(4), 16);
        glm::mat3 r = glm::mat3_cast(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT4_TO_QUAT: {
        glm::mat4 a; memcpy(&a, e.next(16), 64);
        glm::quat r = glm::quat_cast(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_MAT3_TO_QUAT: {
        glm::mat3 a; memcpy(&a, e.next(9), 36);
        glm::quat r = glm::quat_cast(a); memcpy(out, &r, sizeof r);
        break;
    }
    case OP_QUAT_FROM: {
        float s = e.next();
        float t = e.next();
        float u = e.next();
        float v = e.next();
        glm::quat r = glm::quat(s, t, u, v); memcpy(out, &r, sizeof r);
        break;
    }
    default:
        break;
    }
}
